// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxepkcgzmqcataztudci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZXBrY2d6bXFjYXRhenR1ZGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzQwNjUsImV4cCI6MjA1Njk1MDA2NX0.I4IVnA96BM2aT1uzyOIyGusyn5ANUYhT5LbIK7Dv-9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);